import type { Book } from "../types";

const temporaryStorage: Book[] = [
  {
    id: 1,
    name: "1984",
    coverPath: "/images/1984.jpg",
    author: "George Orwell",
    year_published: 1984,
    genres: ["Classics", "Dystopia", "Fiction", "Politics"],
  },
  {
    id: 2,
    name: "The Catcher In The Rye",
    coverPath: "/images/the_catcher_in_the_rye.jpg",
    author: "J.D. Salinger",
    year_published: 1951,
    genres: ["Classics", "Fiction"],
  },
  {
    id: 3,
    name: "The Great Gatsby",
    coverPath: "/images/the_great_gatsby.jpg",
    author: "F. Scott Fitzgerald",
    year_published: 1925,
    genres: ["Classics", "Fiction", "Historical Fiction", "Romance"],
  },
  {
    id: 4,
    name: "To Kill A Mockingbird",
    coverPath: "/images/to_kill_a_mockingbird.jpg",
    author: "Harper Lee",
    year_published: 1960,
    genres: ["Classics", "Fiction", "Historical Fiction"],
  },
  {
    id: 5,
    name: "Animal Farm",
    coverPath: "/images/animal_farm.jpg",
    author: "George Orwell",
    year_published: 1945,
    genres: ["Classics", "Fiction", "Dystopia", "Politics", "Fantasy"],
  },
  {
    id: 6,
    name: "East of Eaden",
    coverPath: "/images/east_of_eaden.jpg",
    author: "John Steinbeck",
    year_published: 1952,
    genres: ["Classics", "Fiction", "Historical Fiction"],
  },
  {
    id: 7,
    name: "Fahrenheit 451",
    coverPath: "/images/fahrenheit_451.jpg",
    author: "Ray Bradbury",
    year_published: 1953,
    genres: ["Classics", "Fiction", "Science Fiction"],
  },
  {
    id: 8,
    name: "1984",
    coverPath: "/images/1984.jpg",
    author: "George Orwell",
    year_published: 1984,
    genres: ["Classics", "Dystopia", "Fiction", "Politics"],
  },
  {
    id: 9,
    name: "The Catcher In The Rye",
    coverPath: "/images/the_catcher_in_the_rye.jpg",
    author: "J.D. Salinger",
    year_published: 1951,
    genres: ["Classics", "Fiction"],
  },
  {
    id: 10,
    name: "The Great Gatsby",
    coverPath: "/images/the_great_gatsby.jpg",
    author: "F. Scott Fitzgerald",
    year_published: 1925,
    genres: ["Classics", "Fiction", "Historical Fiction", "Romance"],
  },
  {
    id: 11,
    name: "To Kill A Mockingbird",
    coverPath: "/images/to_kill_a_mockingbird.jpg",
    author: "Harper Lee",
    year_published: 1960,
    genres: ["Classics", "Fiction", "Historical Fiction"],
  },
  {
    id: 12,
    name: "Animal Farm",
    coverPath: "/images/animal_farm.jpg",
    author: "George Orwell",
    year_published: 1945,
    genres: ["Classics", "Fiction", "Dystopia", "Politics", "Fantasy"],
  },
  {
    id: 13,
    name: "East of Eaden",
    coverPath: "/images/east_of_eaden.jpg",
    author: "John Steinbeck",
    year_published: 1952,
    genres: ["Classics", "Fiction", "Historical Fiction"],
  },
  {
    id: 14,
    name: "Fahrenheit 451",
    coverPath: "/images/fahrenheit_451.jpg",
    author: "Ray Bradbury",
    year_published: 1953,
    genres: ["Classics", "Fiction", "Science Fiction"],
  },
];

export default temporaryStorage;
